### PR TITLE
Consider the full path in changing PUSH to REPLACE

### LINKED ISSUE #166: Same URL with different hash anchor tags are not maintained in history properly
I have a case where I have a bunch of anchors on a page, and want to record when a user navigates between those anchors. With the change in PR #43, it removes that functionality, because now it treats all hash changes on the same page as if they're one single item in the browser history. 

I believe this might be a regression bug according to @taion.

### PR DESCRIPTION
**Pull request by taion**
Fixes #166

Organizing the changelog a bit ahead of adding something for #141 to hopefully make it a bit more usable.

### CODE REVIEW

File: modules/createHistory.js [hunk 1]
```diff
@@ -117,11 +117,10 @@ function createHistory(options={}) {
       if (ok) {
         // treat PUSH to current path like REPLACE to be consistent with browsers
         if (nextLocation.action === PUSH) {
-          let { pathname, search } = getCurrentLocation()
-          let currentPath = pathname + search
-          let path = nextLocation.pathname + nextLocation.search
+          const prevPath = createPath(location)
```
Comment (taion) [inline modules/createHistory.js]: This is not 100% correct, since it doesn't e.g. account for `basename` when using browser history. In practice that's not an issue, though, since `basename` doesn't change.

This should be the "final" `createPath`, but I can't access that here.

**Comment by taurose** [comment]
LGTM. Thanks for tackling that.

As for your question why I used `getCurrentLocation()`, I think I wanted to avoid race conditions and mimic the default browser behavior as close as possible. Right now I can't think of any realistic condition where using `location` instead would be a problem, so I'm good with that change.

**Comment by taion** [comment]
I believe in a base `history`, transitions are fully synchronous, so I don't think race conditions are an issue. Let's go with this for now and patch later if needed.

**Comment by taion** [comment]
@taurose I think there might be a separate related race condition when using async routes in `ReactRouter.useRoutes`, though - i.e. where the transition is async, so the user can e.g. change their mind and try to `PUSH` a separate location while the old routing state is still shown... for browser-mimicking that should get changed to a `REPLACE`, but we can't even handle that in `history` since the route state management is all downstream.

**Comment by taurose** [comment]
@taion Yeah that seems like a feature we lost from 0.13. Since history doesn't deal with data loading (or anything that happens after the URL changes), I'd say this should be handled by the router.

**Comment by taion** [comment]
Yeah, the router can just use `listenBefore`.
